spring: 
  profiles: 
    active: 
    - dev
---
# 注册中心占用7001端口，冒号后面必须要有空格
server: 
  port: 7001
   
spring: 
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client
    
eureka: 
  instance: 
# eureka 服务端的实例名称 已做域名映射
    hostname: eureka7001.com
  client: 
# false 表示不向注册中心注册自己
    register-with-eureka: false
# false 表示自己端就是注册中心，职责是维护服务实例并不需要去检索服务
    fetch-registry: false
# 与 Eureka Server 交互的地址查询服务和注册服务依赖的地址
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
---
server: 
  port: 7001
  application:
    name: microservicecloud-config-eureka-client
   
spring: 
  profiles: test
    
eureka: 
  instance: 
    hostname: eureka7001.com
  client: 
    register-with-eureka: false
    fetch-registry: false
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/

